/* Creamos algunos usuarios con sus roles */
INSERT INTO users (id, username, password, email, create_at, provincia, role) VALUES (1, 'admin', '$2a$10$c4M07uAo.9B6.0fi8RrXV.i0C7NoYIv5PyjD4kHIEmyDZhyWMvxNa', 'admin@gmail.com', NOW(), 'Madrid', 1);
INSERT INTO users (id, username, password, email, create_at, provincia, role) VALUES (2, 'adrian', '$2a$10$GLVrqBoycZdZyDulq6WoZ.EtqU2a5iyog1Ry9zMRAF1R0vFY77aVK', 'adrian@gmail.com', NOW(), 'Barcelona', 2);


/* Rellenamos la tabla 'combustible' */
INSERT INTO combustibles (`id`, `combustible`) VALUES ('1', 'Diésel');
INSERT INTO combustibles (`id`, `combustible`) VALUES ('2', 'Gasolina');
INSERT INTO combustibles (`id`, `combustible`) VALUES ('3', 'Eléctrico');
INSERT INTO combustibles (`id`, `combustible`) VALUES ('4', 'Híbrido');
INSERT INTO combustibles (`id`, `combustible`) VALUES ('5', 'Hibrido enchufable');
INSERT INTO combustibles (`id`, `combustible`) VALUES ('6', 'Gas licuado (GLP)');
INSERT INTO combustibles (`id`, `combustible`) VALUES ('7', 'Gas natural (CNG)');
INSERT INTO combustibles (`id`, `combustible`) VALUES ('8', 'Otros');


/* Rellenamos la tabla 'años' */
INSERT INTO anios (`id`, `anio`) VALUES ('1', '1970');
INSERT INTO anios (`id`, `anio`) VALUES ('2', '1971');
INSERT INTO anios (`id`, `anio`) VALUES ('3', '1972');
INSERT INTO anios (`id`, `anio`) VALUES ('5', '1973');
INSERT INTO anios (`id`, `anio`) VALUES ('6', '1974');
INSERT INTO anios (`id`, `anio`) VALUES ('7', '1975');
INSERT INTO anios (`id`, `anio`) VALUES ('8', '1976');
INSERT INTO anios (`id`, `anio`) VALUES ('9', '1977');
INSERT INTO anios (`id`, `anio`) VALUES ('10', '1978');
INSERT INTO anios (`id`, `anio`) VALUES ('11', '1979');
INSERT INTO anios (`id`, `anio`) VALUES ('12', '1980');
INSERT INTO anios (`id`, `anio`) VALUES ('13', '1981');
INSERT INTO anios (`id`, `anio`) VALUES ('14', '1982');
INSERT INTO anios (`id`, `anio`) VALUES ('15', '1983');
INSERT INTO anios (`id`, `anio`) VALUES ('16', '1984');
INSERT INTO anios (`id`, `anio`) VALUES ('17', '1985');
INSERT INTO anios (`id`, `anio`) VALUES ('18', '1986');
INSERT INTO anios (`id`, `anio`) VALUES ('19', '1987');
INSERT INTO anios (`id`, `anio`) VALUES ('20', '1988');
INSERT INTO anios (`id`, `anio`) VALUES ('21', '1989');
INSERT INTO anios (`id`, `anio`) VALUES ('22', '1990');
INSERT INTO anios (`id`, `anio`) VALUES ('23', '1991');
INSERT INTO anios (`id`, `anio`) VALUES ('24', '1992');
INSERT INTO anios (`id`, `anio`) VALUES ('25', '1993');
INSERT INTO anios (`id`, `anio`) VALUES ('26', '1994');
INSERT INTO anios (`id`, `anio`) VALUES ('27', '1995');
INSERT INTO anios (`id`, `anio`) VALUES ('28', '1996');
INSERT INTO anios (`id`, `anio`) VALUES ('29', '1997');
INSERT INTO anios (`id`, `anio`) VALUES ('30', '1998');
INSERT INTO anios (`id`, `anio`) VALUES ('31', '1999');
INSERT INTO anios (`id`, `anio`) VALUES ('32', '2000');
INSERT INTO anios (`id`, `anio`) VALUES ('33', '2001');
INSERT INTO anios (`id`, `anio`) VALUES ('34', '2002');
INSERT INTO anios (`id`, `anio`) VALUES ('35', '2003');
INSERT INTO anios (`id`, `anio`) VALUES ('36', '2004');
INSERT INTO anios (`id`, `anio`) VALUES ('37', '2005');
INSERT INTO anios (`id`, `anio`) VALUES ('38', '2006');
INSERT INTO anios (`id`, `anio`) VALUES ('39', '2007');
INSERT INTO anios (`id`, `anio`) VALUES ('40', '2008');
INSERT INTO anios (`id`, `anio`) VALUES ('41', '2009');
INSERT INTO anios (`id`, `anio`) VALUES ('42', '2010');
INSERT INTO anios (`id`, `anio`) VALUES ('43', '2011');
INSERT INTO anios (`id`, `anio`) VALUES ('44', '2012');
INSERT INTO anios (`id`, `anio`) VALUES ('45', '2013');
INSERT INTO anios (`id`, `anio`) VALUES ('46', '2014');
INSERT INTO anios (`id`, `anio`) VALUES ('47', '2015');
INSERT INTO anios (`id`, `anio`) VALUES ('48', '2016');
INSERT INTO anios (`id`, `anio`) VALUES ('49', '2017');
INSERT INTO anios (`id`, `anio`) VALUES ('50', '2018');

/* Rellenamos la tabla 'marcas' */
INSERT INTO marcas (`id`, `marca`) VALUES ('1', 'ABARTH');
INSERT INTO marcas (`id`, `marca`) VALUES ('2', 'ALFA ROMEO');
INSERT INTO marcas (`id`, `marca`) VALUES ('3', 'ASIA');
INSERT INTO marcas (`id`, `marca`) VALUES ('4', 'ASTON MARTIN');
INSERT INTO marcas (`id`, `marca`) VALUES ('5', 'AUDI');
INSERT INTO marcas (`id`, `marca`) VALUES ('6', 'BENTLEY');
INSERT INTO marcas (`id`, `marca`) VALUES ('7', 'BERTONE');
INSERT INTO marcas (`id`, `marca`) VALUES ('8', 'BMW');
INSERT INTO marcas (`id`, `marca`) VALUES ('9', 'CADILLAC');
INSERT INTO marcas (`id`, `marca`) VALUES ('10', 'CHEVROLET');
INSERT INTO marcas (`id`, `marca`) VALUES ('11', 'CHRYSLER');
INSERT INTO marcas (`id`, `marca`) VALUES ('12', 'CITROEN');
INSERT INTO marcas (`id`, `marca`) VALUES ('13', 'CORVETTE');
INSERT INTO marcas (`id`, `marca`) VALUES ('14', 'DACIA');
INSERT INTO marcas (`id`, `marca`) VALUES ('15', 'DAEWOO');
INSERT INTO marcas (`id`, `marca`) VALUES ('16', 'DAIHATSU');
INSERT INTO marcas (`id`, `marca`) VALUES ('17', 'DAIMLER');
INSERT INTO marcas (`id`, `marca`) VALUES ('18', 'DFSK');
INSERT INTO marcas (`id`, `marca`) VALUES ('19', 'DODGE');
INSERT INTO marcas (`id`, `marca`) VALUES ('20', 'DS');
INSERT INTO marcas (`id`, `marca`) VALUES ('21', 'FERRARI');
INSERT INTO marcas (`id`, `marca`) VALUES ('22', 'FIAR');
INSERT INTO marcas (`id`, `marca`) VALUES ('23', 'FORD');
INSERT INTO marcas (`id`, `marca`) VALUES ('24', 'GALLOPER');
INSERT INTO marcas (`id`, `marca`) VALUES ('25', 'HONDA');
INSERT INTO marcas (`id`, `marca`) VALUES ('26', 'HUMMER');
INSERT INTO marcas (`id`, `marca`) VALUES ('27', 'HYUNDAI');
INSERT INTO marcas (`id`, `marca`) VALUES ('28 ', 'INFINITI');
INSERT INTO marcas (`id`, `marca`) VALUES ('29', 'INNOCENTI');
INSERT INTO marcas (`id`, `marca`) VALUES ('30', 'ISUZU');
INSERT INTO marcas (`id`, `marca`) VALUES ('31', 'IVECO');
INSERT INTO marcas (`id`, `marca`) VALUES ('32', 'JAGUAR');
INSERT INTO marcas (`id`, `marca`) VALUES ('33', 'JEEP');
INSERT INTO marcas (`id`, `marca`) VALUES ('34', 'KIA');
INSERT INTO marcas (`id`, `marca`) VALUES ('35', 'LADA');
INSERT INTO marcas (`id`, `marca`) VALUES ('36', 'LAMBORGHINI');
INSERT INTO marcas (`id`, `marca`) VALUES ('37', 'LANCIA');
INSERT INTO marcas (`id`, `marca`) VALUES ('38', 'LAND-ROVER');
INSERT INTO marcas (`id`, `marca`) VALUES ('39', 'LDV');
INSERT INTO marcas (`id`, `marca`) VALUES ('40', 'LEXUS');
INSERT INTO marcas (`id`, `marca`) VALUES ('41', 'LOTUS');
INSERT INTO marcas (`id`, `marca`) VALUES ('42', 'MAHINDRA');
INSERT INTO marcas (`id`, `marca`) VALUES ('43', 'MASERATI');
INSERT INTO marcas (`id`, `marca`) VALUES ('44', 'MAYBACH');
INSERT INTO marcas (`id`, `marca`) VALUES ('45', 'MAZDA');
INSERT INTO marcas (`id`, `marca`) VALUES ('46', 'MERCEDES-BENZ');
INSERT INTO marcas (`id`, `marca`) VALUES ('47', 'MG');
INSERT INTO marcas (`id`, `marca`) VALUES ('48', 'MINI');
INSERT INTO marcas (`id`, `marca`) VALUES ('49', 'MITSUBISHI');
INSERT INTO marcas (`id`, `marca`) VALUES ('50', 'MORGAN');
INSERT INTO marcas (`id`, `marca`) VALUES ('51', 'NISSAN');
INSERT INTO marcas (`id`, `marca`) VALUES ('52', 'OPEL');
INSERT INTO marcas (`id`, `marca`) VALUES ('53', 'PEUGEOT');
INSERT INTO marcas (`id`, `marca`) VALUES ('54', 'PIAGGIO');
INSERT INTO marcas (`id`, `marca`) VALUES ('55', 'PONTIAC');
INSERT INTO marcas (`id`, `marca`) VALUES ('56', 'PORSCHE');
INSERT INTO marcas (`id`, `marca`) VALUES ('57', 'RENAULT');
INSERT INTO marcas (`id`, `marca`) VALUES ('58', 'ROLLS-ROYCE');
INSERT INTO marcas (`id`, `marca`) VALUES ('59', 'ROVER');
INSERT INTO marcas (`id`, `marca`) VALUES ('60', 'SAAB');
INSERT INTO marcas (`id`, `marca`) VALUES ('61', 'SANTANA');
INSERT INTO marcas (`id`, `marca`) VALUES ('62', 'SEAT');
INSERT INTO marcas (`id`, `marca`) VALUES ('63', 'SKODA');
INSERT INTO marcas (`id`, `marca`) VALUES ('64', 'SMART');
INSERT INTO marcas (`id`, `marca`) VALUES ('65', 'SSANGYONG');
INSERT INTO marcas (`id`, `marca`) VALUES ('66', 'SUBARU');
INSERT INTO marcas (`id`, `marca`) VALUES ('67', 'SUZUKI');
INSERT INTO marcas (`id`, `marca`) VALUES ('68', 'TALBOT');
INSERT INTO marcas (`id`, `marca`) VALUES ('69', 'TATA');
INSERT INTO marcas (`id`, `marca`) VALUES ('70', 'TESLA');
INSERT INTO marcas (`id`, `marca`) VALUES ('71', 'TOYOTA');
INSERT INTO marcas (`id`, `marca`) VALUES ('72', 'VAZ');
INSERT INTO marcas (`id`, `marca`) VALUES ('73', 'VOLKSWAGEN');
INSERT INTO marcas (`id`, `marca`) VALUES ('74', 'VOLVO');

/* Rellenamos la tabla provincias */

INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (2,'Albacete');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (3,'Alicante/Alacant');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (4,'Almería');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (1,'Araba/Álava');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (33,'Asturias');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (5,'Ávila');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (6,'Badajoz');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (7,'Balears, Illes');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (8,'Barcelona');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (48,'Bizkaia');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (9,'Burgos');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (10,'Cáceres');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (11,'Cádiz');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (39,'Cantabria');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (12,'Castellón/Castelló');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (51,'Ceuta');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (13,'Ciudad Real');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (14,'Córdoba');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (15,'Coruña, A');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (16,'Cuenca');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (20,'Gipuzkoa');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (17,'Girona');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (18,'Granada');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (19,'Guadalajara');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (21,'Huelva');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (22,'Huesca');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (23,'Jaén');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (24,'León');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (27,'Lugo');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (25,'Lleida');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (28,'Madrid');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (29,'Málaga');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (52,'Melilla');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (30,'Murcia');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (31,'Navarra');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (32,'Ourense');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (34,'Palencia');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (35,'Palmas, Las');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (36,'Pontevedra');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (26,'Rioja, La');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (37,'Salamanca');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (38,'Santa Cruz de Tenerife');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (40,'Segovia');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (41,'Sevilla');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (42,'Soria');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (43,'Tarragona');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (44,'Teruel');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (46,'Valencia/València');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (47,'Valladolid');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (49,'Zamora');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (50,'Zaragoza');
INSERT INTO provincias (`id_provincia`, `provincia`) VALUES (45,'Toledo');

/* Agregamos unos anuncios */
INSERT INTO vehiculos (`id`, `anio`, `color`, `combustible`, `descripcion`, `foto`, `id_user`, `kilometros`, `marca`, `modelo`, `precio`, `provincia`, `puertas`, `tipo_cambio`) VALUES ('1', '2015', 'Blanco', 'Diésel', 'Vendo coche en buen estado, poco uso muy cuidado', '6ab52474-f98a-418d-8ae2-98c387a4a475_ibiza.jpg', '2', '77500', 'Seat', 'Ibiza', '12500', 'Barcelona', '5', 'Manual');
INSERT INTO vehiculos (`id`, `anio`, `color`, `combustible`, `descripcion`, `foto`, `id_user`, `kilometros`, `marca`, `modelo`, `precio`, `provincia`, `puertas`, `tipo_cambio`) VALUES ('2', '2010', 'Gris', 'Gasolina', 'Vehiculo muy cuidado esta tal y como se ve en las fotos, funciona como un reloj, tiene un consumo y un mantenimiento muy bajo.', '44c7ef65-b430-44bf-b667-391f54652034_opel.jpg', '2', '14700', 'Opel', 'Astra', '7400', 'Barcelona', '5', 'Manual');
INSERT INTO vehiculos (`id`, `anio`, `color`, `combustible`, `descripcion`, `foto`, `id_user`, `kilometros`, `marca`, `modelo`, `precio`, `provincia`, `puertas`, `tipo_cambio`) VALUES ('3', '2013', 'Blanco', 'Gasolina', 'BMW X5 3.0D xDrive ,!! Impecable-FullEquipe !!diesel 6 cilindros 245Cv de potencia ,consumo medio 7,4L/100Km.Kilomteros Certificados Historial completo en BMW.Procede de particular Unico propietario,vehiculo Nacional .Fecha!', '55a7652f-6afb-4a26-87ec-aff355a60815_bmw.jpg', '1', '125000', 'BMW', '330i', '18600', 'Madrid', '3', 'Automatico');
INSERT INTO vehiculos (`id`, `anio`, `color`, `combustible`, `descripcion`, `foto`, `id_user`, `kilometros`, `marca`, `modelo`, `precio`, `provincia`, `puertas`, `tipo_cambio`) VALUES ('4', '2014', 'Azul', 'Híbrido', 'ABS, Airbag conductor, Airbag de rodillas conductor, Airbag exterior delantero para peatones, Airbag lateral conductor y pasajero, Airbag pasajero, Airbags de cabeza delanteros, Airbags de cabeza traseros', '79f7ed85-e970-46ec-b795-07c454880c43_volvo.jpg', '1', '178000', 'VOLVO', 'v40', '22630', 'Madrid', '5', 'Automatico');
INSERT INTO vehiculos (`id`, `anio`, `color`, `combustible`, `descripcion`, `foto`, `id_user`, `kilometros`, `marca`, `modelo`, `precio`, `provincia`, `puertas`, `tipo_cambio`) VALUES ('5', '2011', 'Granate', 'Diésel', 'Es un vehículo perfecto para todo tipo de uso, desde un uso mayoritario por la urbe a poder realizar grandes viajes con él.', '430caf4d-6bc6-4112-94d9-15199034ae07_a3.jpg', '2', '156234', 'AUDI', 'A3', '13500', 'Barcelona', '5', 'Manual');
INSERT INTO vehiculos (`id`, `anio`, `color`, `combustible`, `descripcion`, `foto`, `id_user`, `kilometros`, `marca`, `modelo`, `precio`, `provincia`, `puertas`, `tipo_cambio`) VALUES ('6', '2014', 'Azul', 'Gasolina', 'En stock con entrega inmediata - - Vehículo con CERTIFICADO Citroën Select revisado en más de 93 puntos -- Kilometraje Certificado.- Fecha de matriculación: 06/2017 - Garantía Oficial mínimo 12 meses', '0538f98a-3897-41ed-812d-28d269864757_leon.jpg', '1', '72566', 'SEAT', 'Leon', '11600', 'Madrid', '5', 'Manual');


